<?xml version="1.0"?>
<robot name="smartcar" xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:property name="wheelbase_length" value = "0.257"/>
<xacro:property name="wheelbase_width" value = "0.17"/>
<xacro:property name="wheelbase_height" value = "0.05"/>

<xacro:property name="wheel_diameter" value="0.064"/>
<xacro:property name="wheel_width" value="0.025"/>

<!--inertia property macros-->
<xacro:macro name="box_inertia" params="m w h d">
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${m}"/>
        <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
</xacro:macro>

<xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy="0" ixz="0" iyy="${(m/12) * (3*r*r + h*h)}" iyz="0" izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>

<!--base-->

<link name="base_link">
    <visual>
        <origin xyz = "0 0 ${wheelbase_height/2}" rpy = "0 0 0"/>
        <geometry>
        <box size="${wheelbase_length} ${wheelbase_width} ${wheelbase_height}"/>
        </geometry>
    </visual>
    <collision>
    <origin xyz = "0 0 ${wheelbase_height/2}" rpy = "0 0 0"/>
        <geometry>
        <box size="${wheelbase_length} ${wheelbase_width} ${wheelbase_height}"/>
        </geometry>
    </collision>
    <xacro:box_inertia m="0.1" w="${wheelbase_width}" d="${wheelbase_length}" h="${wheelbase_height}"/>
</link>

<link name="base_footprint">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="0.001 0.001 0.001"/>
        </geometry>
    </visual>
</link>

<joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 -${wheel_diameter/2}" rpy="0 0 0"/>
</joint>

<link name="chassis_link">
    <visual>
        <origin xyz="0 0 ${wheelbase_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${wheelbase_length} ${wheelbase_width} ${wheelbase_height}"/>
        </geometry>
    </visual>
    <collision>
        <origin xyz="0 0 ${wheelbase_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${wheelbase_length} ${wheelbase_width} ${wheelbase_height}"/>
        </geometry>
    </collision>
    <xacro:box_inertia m="1.0" w="${wheelbase_width}" d="${wheelbase_length}" h="${wheelbase_height}"/>
</link>

<joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>

<!-- Wheels -->
<xacro:macro name="wheel" params="prefix x_reflect y_reflect joint_name">
<link name="${prefix}_link">
    <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
            <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
        </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.1" r="${wheel_diameter/2}" h="${wheel_width}"/>
</link>

<joint name="${joint_name}" type="continuous">
    <parent link="base_link"/>
    <child link="${prefix}_link"/>
    <origin xyz="${-x_reflect * wheelbase_length/2} ${(y_reflect * (wheelbase_width/2 + wheel_width/2))} ${wheelbase_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
</joint>
</xacro:macro>

<!-- Front Wheels with Steering -->
<xacro:macro name="steering_wheel" params="prefix x_reflect y_reflect steer_joint_name wheel_joint_name">
<link name="${prefix}_steer_link">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="0.01 0.01 0.01"/>
        </geometry>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="0.01 0.01 0.01"/>
        </geometry>
    </collision>
    <xacro:box_inertia m="0.01" w="0.01" d="0.01" h="0.01"/>
</link>

<joint name="${steer_joint_name}" type="revolute">
    <parent link="base_link"/>
    <child link="${prefix}_steer_link"/>
    <origin xyz="${-x_reflect * wheelbase_length/2} ${(y_reflect * (wheelbase_width/2 + wheel_width/2))} ${wheelbase_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.785" upper="0.785" effort="1000" velocity="100"/>
    <dynamics damping="0.5" friction="0.5"/>
</joint>

<link name="${prefix}_link">
    <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
            <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
        </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.1" r="${wheel_diameter/2}" h="${wheel_width}"/>
</link>

<joint name="${wheel_joint_name}" type="continuous">
    <parent link="${prefix}_steer_link"/>
    <child link="${prefix}_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
</joint>
</xacro:macro>

<xacro:wheel prefix="back_left_wheel" x_reflect="1" y_reflect="1" joint_name="back_left_wheel_joint"/>
<xacro:wheel prefix="back_right_wheel" x_reflect="1" y_reflect="-1" joint_name="back_right_wheel_joint"/>
<xacro:steering_wheel prefix="front_left_wheel" x_reflect="-1" y_reflect="1" steer_joint_name="front_left_wheel_steer_joint" wheel_joint_name="front_left_wheel_joint"/>
<xacro:steering_wheel prefix="front_right_wheel" x_reflect="-1" y_reflect="-1" steer_joint_name="front_right_wheel_steer_joint" wheel_joint_name="front_right_wheel_joint"/>

<!-- IMU Sensor Macro -->
<xacro:macro name="imu_sensor">
  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.05"/> 
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.02"/>
      <origin xyz="0 0 0"/>
    </inertial>
  </link>
  
  <joint name="imu_joint" type="fixed">
    <parent link="base_link" />
    <child link="imu_link"/>
    <origin xyz="0 0 ${wheelbase_height/2}"/>
  </joint>

  <gazebo reference="imu_link">
    <sensor type="imu" name="imu_sensor">
      <always_on>true</always_on>
      <update_rate>30.0</update_rate>
      <plugin name="gazebo_ros_imu" filename="libgazebo_ros_imu_sensor.so">
        <ros>
          <remapping>~/out:=/imu_data</remapping>
        </ros>
      </plugin>
    </sensor>
  </gazebo>

</xacro:macro>

<xacro:macro name="lidar_sensor">
<xacro:property name="LiDAR_radius" value="0.03"/>
<link name="sllidar_base_link">
    <visual>
      <geometry>
        <cylinder radius="${LiDAR_radius}" length="0.05"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${LiDAR_radius}" length="0.05"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.05"/> 
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.02"/>
      <origin xyz="0 0 0"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link" />
    <child link="sllidar_base_link"/>
    <origin xyz="${wheelbase_length / 2} 0 ${wheel_diameter / 2 + 0.05}"/>
  </joint>

  <gazebo reference="sllidar_base_link">
    <sensor name="lidar" type="ray">
      <pose> 0 0 0 0 0 0 </pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
          <scan>
              <horizontal>
                  <samples>360</samples>
                  <min_angle>-${pi}</min_angle>
                  <max_angle>${pi}</max_angle>
              </horizontal>
          </scan>
          <range>
              <min>0.3</min>
              <max>12</max>
          </range>
      </ray>
      <plugin name="lidar_plugin" filename="libgazebo_ros_ray_sensor.so">
          <ros>
              <argument>~/out:=scan</argument>
          </ros>
          <output_type>sensor_msgs/LaserScan</output_type>
          <frame_name>sllidar_base_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>
</xacro:macro>

<!-- Include the sensors -->
<xacro:imu_sensor/>
<xacro:lidar_sensor/>

<!-- Car Gazebo Plugin -->
<gazebo>
  <plugin name="car_gazebo_plugin" filename="libcar_gazebo_plugin.so">
  </plugin>
</gazebo>

</robot>